AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - '*.gemspec'
    - 'Gemfile'
    - 'Gemfile.lock'

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
